package:  headsupgrid
version:  '1'
author:   Oliver Kreischer
supportpage: https://github.com/olien/headsupgrid/issues

page:
    title: 'translate:title'
    perm: headsupgrid[]
    icon: rex-icon fa-reorder
    subpages:
      info: { title: 'translate:info'}
      settings: { title: 'translate:settings'}
      changelog: { title: 'translate:changelog'}
      license: { title: 'translate:license'}
